import = ["~/.config/alacritty/alacritty-theme/themes/tokyo-night-storm.toml"]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic" }
size = 16

[terminal]
osc52 = "CopyPaste"
