import = ["~/.config/alacritty/alacritty-theme/themes/tokyo-night-storm.toml"]

[window]
padding.x = 10
padding.y = 10

decorations = "buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font"

size = 16
